### PR TITLE
improve metadata, incl. contributors of modelling/data

### PR DESCRIPTION
**Pull request by acocac**
@scotthosking, following your suggestion, I have an improved version of the notebooks with further metadata, including details of the modelling/data contributors, funding and related publications.

Note I'm importing the references from the `_bibliography/references.bib` file which will make easier to maintain future related publications of each notebook.

I would appreciate confirming if the proposed metadata looks ok for you (:

### CODE REVIEW

**Comment by scotthosking** [comment]
Hi Alejandro, thanks for sending me the updates of your EnvAI book! A few comment from me :blush:
regarding this page: https://acocac.github.io/environmental-ai-book/forest/modelling/forest-modelling-treecrown_deepforest.html

- those named under "Codebase" needs reviewing - Ben and Henry are not at BAS, and Tony is not involved as far as I know. Maybe this was just a placeholder?

- Generally - might it make sense to combine authors and reviewers under one heading? I guess the reviewers do offer suggestions which end up in the final version? If someone was to cite this notebook would it be more proper to cite as "Coca-Castro and Allen (2021)" ? - to acknowledge Matt's contribution and his original piece of research?

**Comment by scotthosking** [comment]
re: https://acocac.github.io/environmental-ai-book/forest/modelling/forest-modelling-treecrown_detectree.html

- the acknowledgements look good here. Can we provide a hyperlink to the AI4ER CDT website?

**Comment by scotthosking** [comment]
I suggest we remove the Digital Twins sections until we have something to include - best to have fewer sections with content, and add new sections later when we have something to include/show

**Comment by acocac** [comment]
> Hi Alejandro, thanks for sending me the updates of your EnvAI book! A few comment from me 😊 regarding this page: https://acocac.github.io/environmental-ai-book/forest/modelling/forest-modelling-treecrown_deepforest.html

Thanks @scotthosking for the feedback! Please find my comments below for each of yours points.

> 
> * those named under "Codebase" needs reviewing - Ben and Henry are not at BAS, and Tony is not involved as far as I know. Maybe this was just a placeholder?

Good you spotted it. I'll modify the affiliations with the correct institutions. 

> * Generally - might it make sense to combine authors and reviewers under one heading? I guess the reviewers do offer suggestions which end up in the final version? If someone was to cite this notebook would it be more proper to cite as "Coca-Castro and Allen (2021)" ? - to acknowledge Matt's contribution and his original piece of research?

Still WIP but this is a great idea to ensure credits for authors and reviewers.

**Comment by acocac** [comment]
> * AI4ER CDT website

Done!

**Comment by acocac** [comment]
> I suggest we remove the Digital Twins sections until we have something to include - best to have fewer sections with content, and add new sections later when we have something to include/show

Agreed, happy to add any future progress from BAS when available.

**Comment by acocac** [comment]
related to [issue#11](https://github.com/acocac/environmental-ai-book/issues/11)

**Pull request merged**
